name: Deploy to EC2

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure SSH
      uses: shimat/setup-ssh-action@v1.2.1
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy to EC2
      run: |
        # Add the commands to deploy the code to the EC2 server
        # For example:
        ssh -i ~/.ssh/id_rsa ubuntu@${{ secrets.AWS_EC2_IP }}
        cd takealook
        forever stop 0
        forever start bin/www
